# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationinvitation',
            name='organization',
        ),
        migrations.DeleteModel(
            name='OrganizationInvitation',
        ),
    ]
